
namespace Dodoco.Core.Game;

public enum GameUpdateManagerState {

    UPDATED,
    DOWNLOADING_UPDATE_PACKAGE,
    UNZIPPING_UPDATE_PACKAGE,
    APPLYING_UPDATE_PACKAGE,
    REMOVING_DEPRECATED_FILES

}